Update on timer interval
michaelahern/homebridge-airthings pull request #15
Opened 2022-04-02 16:40 UTC by ninjas28

This fixes #14.
See what you think of this, this is a pretty major rewrite of the entire plugin.
I've been running it for about a week now and its been rock solid.

2022-04-04 00:28 UTC, michaelahern commented
Looks great from a quick read through! Give me a bit of time to run it on my end as well, and will post some comments in the meantime..

2022-04-04 00:33 UTC, michaelahern requested changes

2022-04-04 00:33 UTC, michaelahern commented on README.md
> +**refreshInterval**	| (required) Refresh interval for grabbing new data in seconds
Could this be flagged as optional, defaulting to 5 minutes?

2022-04-04 00:33 UTC, michaelahern commented on config.schema.json
> +        "required": true
Could this be flagged as optional, with a [placeholder value](https://developers.homebridge.io/#/config-schema#placeholder-values) of 5 minutes?

2022-04-04 00:33 UTC, michaelahern commented on src/plugin.ts
> +    this.log.info(`Refresh Interval: ${config.refreshInterval}`)
Append "s" so the log shows the value is in seconds.

2022-04-04 02:50 UTC, ninjas28 commented
How's this look?

2022-06-08 17:04 UTC, ninjas28 commented
Have you had a chance to test this out?

FWIW I've been running this for the last couple months and its worked flawlessly.

2022-07-03 21:58 UTC, merged

2022-07-05 00:16 UTC, michaelahern commented
Apologies, took a bit of time, but finally got this merged in. Thanks for the contrib!